spring.application.name=warehouse-management

spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db
spring.datasource.username=postgres
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

t

server.port=8080